IF OBJECT_ID(N'[dbo].[BAYRAK_{{FIRMA}}_{{DONEM}}_BANKARAPOR]', N'V') IS NOT NULL DROP VIEW [dbo].[BAYRAK_{{FIRMA}}_{{DONEM}}_BANKARAPOR];
GO
CREATE VIEW [dbo].[BAYRAK_{{FIRMA}}_{{DONEM}}_BANKARAPOR] AS 
SELECT [Banka Kodu],[Banka Adı],[Hesap Kodu],[Hesap Adı],[Özel Kod],abs(Bakiye) as [TL Bakiye],CASE WHEN Bakiye<0 THEN '(A)' WHEN Bakiye>0 THEN '(B)' ELSE ''  END [Bakiye Tipi],[Döviz Türü],
CASE WHEN ISNULL(KURLAR.RATES2,0)=0 THEN Bakiye ELSE Bakiye / NULLIF(KURLAR.RATES2,0) END AS [Döviz Tutarı]
FROM (
SELECT TOP 1000000
BNCARD.CODE  [Banka Kodu],
BNCARD.DEFINITION_ as [Banka Adı],
CC.CODE AS [Hesap Kodu],
CC.DEFINITION_ AS [Hesap Adı],
ISNULL(TOPLAM.Bakiye,0) AS [Bakiye],
case when  CC.CURRENCY IN(0,160) THEN 'TL' ELSE  DOVIZ.CURCODE END AS [Döviz Türü],CC.SPECODE AS [Özel Kod]
FROM     LG_{{FIRMA}}_BANKACC  CC  LEFT JOIN LG_{{FIRMA}}_BNCARD BNCARD ON BNCARD.LOGICALREF = CC.BANKREF
LEFT JOIN L_CURRENCYLIST  DOVIZ ON DOVIZ.CURTYPE= CC.CURRENCY AND DOVIZ.FIRMNR='{{FIRMA}}'
LEFT JOIN 
(
SELECT TOPLAM.CARDREF,ROUND(SUM(toplam.DEBIT-TOPLAM.CREDIT),2) AS [Bakiye]  
FROM LG_{{FIRMA}}_{{DONEM}}_BNTOTFIL  TOPLAM   WHERE  TOPLAM.TOTTYP  IN (1,4)  
GROUP BY TOPLAM.CARDREF
) TOPLAM ON TOPLAM.CARDREF = CC.LOGICALREF
WHERE   CC.SPECODE  IN('BAKIYE','FON')

) AS TMP

OUTER APPLY
(
select LIST.CURCODE,KUR.RATES2 
from L_CURRENCYLIST  LIST
OUTER APPLY (SELECT TOP 1 KUR.RATES2  FROM LG_EXCHANGE_{{FIRMA}} KUR WHERE KUR.CRTYPE=LIST.CURTYPE   ORDER  BY KUR.EDATE DESC)   KUR
WHERE LIST.FIRMNR='{{FIRMA}}' AND KUR.RATES2 IS NOT NULL
 AND LIST.CURCODE =TMP.[Döviz Türü]
) AS KURLAR
GO
