IF OBJECT_ID(N'[dbo].[BAYRAK_{{FIRMA}}_{{DONEM}}_CARIBAKIYELER]', N'V') IS NOT NULL DROP VIEW [dbo].[BAYRAK_{{FIRMA}}_{{DONEM}}_CARIBAKIYELER];
GO
CREATE VIEW [dbo].[BAYRAK_{{FIRMA}}_{{DONEM}}_CARIBAKIYELER] AS
SELECT
  CASE WHEN CLCARD.ACTIVE=0 THEN N'Kullanımda' ELSE N'Kullanım Dışı' END AS [Kullanım Durum],
  CLCARD.CODE AS [Cari Kodu],
  CLCARD.DEFINITION_ AS [Cari Adı],
  CLCARD.SPECODE AS [Cari Özel Kod],
  CLCARD.SPECODE2 AS [Cari Özel Kod2],
  CLCARD.SPECODE3 AS [Cari Özel Kod3],
  EKSTRE.DATE_ AS [Tarih],
  EKSTRE.TRANNO AS [Fiş No],
  ISNULL(EKSTRE.DEBIT,0) AS [Borç],
  ISNULL(EKSTRE.CREDIT,0) AS [Alacak],
  CASE WHEN ISNULL(EKSTRE.DEBIT,0)>0 THEN EKSTRE.DEBIT ELSE -ISNULL(EKSTRE.CREDIT,0) END AS [Bakiye]
FROM LV_{{FIRMA}}_{{DONEM}}_CLEKSTRE EKSTRE WITH(NOLOCK)
INNER JOIN LG_{{FIRMA}}_CLCARD CLCARD ON CLCARD.LOGICALREF = EKSTRE.CLIENTREF
WHERE EKSTRE.CANCELLED = 0 AND EKSTRE.PAIDINCASH = 0
GO
