IF OBJECT_ID(N'[dbo].[BAYRAK_{{FIRMA}}_{{DONEM}}_HIZMETRAPOR]', N'V') IS NOT NULL DROP VIEW [dbo].[BAYRAK_{{FIRMA}}_{{DONEM}}_HIZMETRAPOR];
GO
CREATE VIEW [dbo].[BAYRAK_{{FIRMA}}_{{DONEM}}_HIZMETRAPOR] AS 


select     
CLCARD.CODE AS [Cari Hesap Kodu],
CLCARD.DEFINITION_ AS [Cari Hesap Adı],
CLCARD.SPECODE AS [Cari Özel Kod],CLCARD.SPECODE2 AS [Cari Özel Kod2],CLCARD.SPECODE3 AS [Cari Özel Kod3],CLCARD.SPECODE4 AS [Cari Özel Kod4],CLCARD.SPECODE5 AS [Cari Özel Kod5],
ISYERI.NR AS [İş Yeri No],
ISYERI.NAME AS [İş Yeri],
AMBAR.NAME as [Depo Adı],
INVOICE.FICHENO AS [Fatura No],
INVOICE.DOCODE  AS [Belge No],
INVOICE.SPECODE AS [Özel Kod],
INVOICE.DATE_ AS [Tarih],
year(INVOICE.DATE_)  [Yıl],
RIGHT('00'+CAST(MONTH(INVOICE.DATE_) AS NVARCHAR(100)),2)+'-'+
CASE MONTH(INVOICE.DATE_)
    WHEN 1 THEN 'Ocak'
    WHEN 2 THEN 'Şubat'
    WHEN 3 THEN 'Mart'
    WHEN 4 THEN 'Nisan'
    WHEN 5 THEN 'Mayıs'
    WHEN 6 THEN 'Haziran'
    WHEN 7 THEN 'Temmuz'
    WHEN 8 THEN 'Ağustos'
    WHEN 9 THEN 'Eylül'
    WHEN 10 THEN 'Ekim'
    WHEN 11 THEN 'Kasım'
    WHEN 12 THEN 'Aralık'
END AS [Ay],
CASE
    WHEN INVOICE.TRCODE IN (1,4,5,13) THEN 'Gider'
    WHEN INVOICE.TRCODE IN (6) THEN 'Gelir' 
    WHEN INVOICE.TRCODE IN (7,8,9,10,14,26) THEN 'Gelir'
    WHEN INVOICE.TRCODE IN (2,3) THEN 'Gider'  
    ELSE ''
END AS [Gelir/Gider],
CASE
    WHEN INVOICE.TRCODE = 1  THEN 'Satın Alma Faturası'
    WHEN INVOICE.TRCODE = 2  THEN 'Perakende Satış İade Faturası'
    WHEN INVOICE.TRCODE = 3  THEN 'Toptan Satış İade Faturası'
    WHEN INVOICE.TRCODE = 4  THEN 'Alınan Hizmet Faturası'
    WHEN INVOICE.TRCODE = 5  THEN 'Alınan Proforma Fatura'
    WHEN INVOICE.TRCODE = 6  THEN 'Alım İade Faturası'
    WHEN INVOICE.TRCODE = 7  THEN 'Perakende Satış Faturası'
    WHEN INVOICE.TRCODE = 8  THEN 'Toptan Satış Faturası'
    WHEN INVOICE.TRCODE = 9  THEN 'Verilen Hizmet Faturası'
    WHEN INVOICE.TRCODE = 10 THEN 'Verilen Proforma Fatura'
    WHEN INVOICE.TRCODE = 13 THEN 'Alınan Fiyat Farkı Faturası'
    WHEN INVOICE.TRCODE = 14 THEN 'Verilen Fiyat Farkı Faturası'
    WHEN INVOICE.TRCODE = 26 THEN 'Müstahsil Makbuzu'
    ELSE ''
END AS [Fatura Türü],
SATIS.CODE AS [Satış Elemanı],
CASE STLINE.LINETYPE 
WHEN 0 THEN 'Malzeme' 
WHEN 1 THEN 'Promosyon' 
WHEN 2 THEN 'İndirim' 
WHEN 3 THEN 'Masraf' 
WHEN 4 THEN 'Hizmet' 
WHEN 5 THEN 'Depozito' 
WHEN 6 THEN 'Karma Koli' 
WHEN 7 THEN 'Karma Koli Kalemi' 
WHEN 8 THEN 'Sabit Kıymet' 
WHEN 9 THEN 'Ek Malzeme' 
WHEN 10 THEN 'Malzeme sınıfı'
WHEN 11 THEN 'Fason' ELSE '' END AS [Satır Türü],
ITEMS.CODE as [Hizmet Kodu],
ITEMS.DEFINITION_ AS [Hizmet Adı],
ITEMS.SPECODE  AS [Hizmet Özel Kod],
ITEMS.SPECODE2 AS [Hizmet Özel Kod2],
ITEMS.SPECODE3 AS [Hizmet Özel Kod3],
ITEMS.SPECODE4 AS [Hizmet Özel Kod4],
ITEMS.SPECODE5 AS [Hizmet Özel Kod5],
BIRIM.CODE AS [Ana Birim],
STLINE.AMOUNT*(CASE WHEN STLINE.UINFO2=0 THEN 1 ELSE STLINE.UINFO2 END/CASE WHEN STLINE.UINFO1=0 THEN 1 ELSE STLINE.UINFO1 END ) [Ana Birim Miktar],
STLINE.LINENET  AS [Net Tutar] 

 

from LG_{{FIRMA}}_{{DONEM}}_STLINE  STLINE        WITH(NOLOCK) LEFT JOIN   LG_{{FIRMA}}_{{DONEM}}_STFICHE  STFICHE WITH (NOLOCK) ON STFICHE.LOGICALREF = STLINE.STFICHEREF
LEFT JOIN LG_{{FIRMA}}_SRVCARD  ITEMS        WITH(NOLOCK) ON ITEMS.LOGICALREF = STLINE.STOCKREF
INNER JOIN LG_{{FIRMA}}_{{DONEM}}_INVOICE  INVOICE WITH(NOLOCK) ON INVOICE.LOGICALREF = STLINE.INVOICEREF
LEFT JOIN LG_{{FIRMA}}_CLCARD CLCARD       WITH(NOLOCK) ON CLCARD.LOGICALREF = STLINE.CLIENTREF
LEFT JOIN LG_{{FIRMA}}_UNITSETL BIRIM      WITH(NOLOCK) ON BIRIM.UNITSETREF = ITEMS.UNITSETREF AND  BIRIM.MAINUNIT=1
LEFT JOIN LG_SLSMAN SATIS            WITH(NOLOCK) ON SATIS.LOGICALREF = STLINE.SALESMANREF
LEFT JOIN L_CAPIWHOUSE AMBAR         WITH(NOLOCK) ON AMBAR.NR = STLINE.SOURCEINDEX  AND AMBAR.FIRMNR='{{FIRMA}}'
LEFT JOIN LG_{{FIRMA}}_UNITSETL SATIRBIRIM WITH(NOLOCK) ON  SATIRBIRIM.LOGICALREF = STLINE.UOMREF 
LEFT JOIN L_CAPIDIV   ISYERI ON ISYERI.NR = INVOICE.BRANCH   AND ISYERI.FIRMNR='{{FIRMA}}' 
WHERE STLINE.TRCODE  IN (2,3,7,8,1,4,9) AND   STLINE.CANCELLED=0 AND STLINE.LINETYPE  IN (4)    AND INVOICE.DEVIR=0
GO
