IF OBJECT_ID(N'[dbo].[BAYRAK_{{FIRMA}}_{{DONEM}}_KDVRAPOR]', N'V') IS NOT NULL DROP VIEW [dbo].[BAYRAK_{{FIRMA}}_{{DONEM}}_KDVRAPOR];
GO
CREATE VIEW [dbo].[BAYRAK_{{FIRMA}}_{{DONEM}}_KDVRAPOR] AS

SELECT
  CASE
    WHEN EMUHACC.CODE LIKE '191%' THEN N'İndirilecek KDV'
    WHEN EMUHACC.CODE LIKE '391%' THEN N'Hesaplanan KDV'
    WHEN EMUHACC.CODE LIKE '190%' THEN N'İndirilecek KDV (Diğer)'
    WHEN EMUHACC.CODE LIKE '390%' THEN N'Hesaplanan KDV (Diğer)'
    ELSE N'Diğer KDV'
  END AS [KDV Türü],
  EMFICHE.DATE_ AS [Tarih],
  YEAR(EMFICHE.DATE_) AS [Yıl],
  RIGHT('00' + CAST(MONTH(EMFICHE.DATE_) AS NVARCHAR(100)), 2) + '-' +
  CASE MONTH(EMFICHE.DATE_)
    WHEN 1 THEN N'Ocak'
    WHEN 2 THEN N'Şubat'
    WHEN 3 THEN N'Mart'
    WHEN 4 THEN N'Nisan'
    WHEN 5 THEN N'Mayıs'
    WHEN 6 THEN N'Haziran'
    WHEN 7 THEN N'Temmuz'
    WHEN 8 THEN N'Ağustos'
    WHEN 9 THEN N'Eylül'
    WHEN 10 THEN N'Ekim'
    WHEN 11 THEN N'Kasım'
    WHEN 12 THEN N'Aralık'
  END AS [Ay],
  CASE EMFLINE.TRCODE
    WHEN 1 THEN N'Açılış Fişi'
    WHEN 2 THEN N'Tahsil Fişi'
    WHEN 3 THEN N'Tediye Fişi'
    WHEN 4 THEN N'Mahsup Fişi'
    WHEN 5 THEN N'Özel Fiş'
    WHEN 6 THEN N'Kur Farkı Fişi'
    WHEN 7 THEN N'Kapanış Fişi'
    WHEN 8 THEN N'Enflasyon Muhasebe Fişi'
    WHEN 9 THEN N'Konsolidasyon Düzeltme Fişi'
    WHEN 10 THEN N'Tfrs Düzeltme Fişi'
    ELSE N''
  END AS [Fiş Türü],
  ISNULL(EMFICHE.FICHENO, '') AS [Fiş No],
  ISNULL(EMFICHE.JOURNALNO, '') AS [Yevmiye No],
  ISNULL(EMFICHE.GENEXP1 + EMFICHE.GENEXP2 + EMFICHE.GENEXP3 + EMFICHE.GENEXP4, '') AS [Genel Açıklama],
  EMUHACC.CODE AS [Hesap Kodu],
  EMUHACC.DEFINITION_ AS [Hesap Adı],
  EMFLINE.DEBIT AS [Borç],
  EMFLINE.CREDIT AS [Alacak],
  CASE WHEN EMFLINE.SIGN = 0 THEN EMFLINE.DEBIT ELSE -EMFLINE.CREDIT END AS [Borç / Alacak],
  CASE EMFICHE.MODULENR
    WHEN 0 THEN N'Kaynak Fiş Türü Olmayanlar'
    WHEN 1 THEN N'Malzeme'
    WHEN 2 THEN N'Satınalma'
    WHEN 3 THEN N'Satış ve Dağıtım'
    WHEN 4 THEN N'Cari Hesap Fişleri'
    WHEN 5 THEN N'Çek/Senet'
    WHEN 6 THEN N'Banka Fişleri'
    WHEN 7 THEN N'Kasa'
    WHEN 10 THEN N'Personel Ödemeleri'
    WHEN 25 THEN N'Sabit Kıymet'
    WHEN 103 THEN N'SMM Mahsubu'
    ELSE N''
  END AS [Modül Adı],
  ISNULL(ISYERI.NR, EMFICHE.BRANCH) AS [İş Yeri No],
  ISNULL(ISYERI.NAME, '') AS [İş Yeri]
FROM dbo.LG_{{FIRMA}}_{{DONEM}}_EMFLINE EMFLINE WITH (NOLOCK)
INNER JOIN dbo.LG_{{FIRMA}}_{{DONEM}}_EMFICHE EMFICHE WITH (NOLOCK)
  ON EMFICHE.LOGICALREF = EMFLINE.ACCFICHEREF
LEFT JOIN dbo.LG_{{FIRMA}}_EMUHACC EMUHACC WITH (NOLOCK)
  ON EMUHACC.LOGICALREF = EMFLINE.ACCOUNTREF
LEFT JOIN dbo.L_CAPIDIV ISYERI WITH (NOLOCK)
  ON ISYERI.NR = EMFICHE.BRANCH AND ISYERI.FIRMNR = '{{FIRMA}}'
WHERE EMFLINE.CANCELLED = 0
  AND EMFICHE.CANCELLED = 0
  AND (
    EMUHACC.CODE LIKE '191%'
    OR EMUHACC.CODE LIKE '391%'
    OR EMUHACC.CODE LIKE '190%'
    OR EMUHACC.CODE LIKE '390%'
  )
GO
