IF OBJECT_ID(N'[dbo].[BAYRAK_{{FIRMA}}_{{DONEM}}_MUHASEBERAPOR]', N'V') IS NOT NULL DROP VIEW [dbo].[BAYRAK_{{FIRMA}}_{{DONEM}}_MUHASEBERAPOR];
GO
CREATE VIEW [dbo].[BAYRAK_{{FIRMA}}_{{DONEM}}_MUHASEBERAPOR] AS 


Select  	
[İş Yeri No] = CASE EMUHACC.CODE
    WHEN '760.01.01.001' THEN 0
    WHEN '760.03.01.001' THEN 1
    WHEN '760.02.01.001' THEN 5
    WHEN '770.00.01.001' THEN 6
    WHEN '760.04.01.001' THEN 7
    WHEN '740.20.01.001' THEN 8
    WHEN '740.21.01.001' THEN 9
    WHEN '740.23.01.001' THEN 11
    WHEN '760.05.01.001' THEN 12
    WHEN '740.22.01.001' THEN 14
END,

[İş Yeri] = CASE EMUHACC.CODE
    WHEN '760.01.01.001' THEN 'LİMAN ENZA'
    WHEN '760.03.01.001' THEN 'KUMLUCA ENZA'
    WHEN '760.02.01.001' THEN 'GAZİ BULVARI ENZA'
    WHEN '770.00.01.001' THEN 'ERYAP MERKEZ YÖNETİM'
    WHEN '760.04.01.001' THEN 'ESKİ SANAYİ YATAŞ BEDDİNG'
    WHEN '740.20.01.001' THEN 'LEAFPORT KONYAALTI HOTEL'
    WHEN '740.21.01.001' THEN 'LEAF RİVER HOTEL'
    WHEN '740.23.01.001' THEN 'KEMER VİLLALAR'
    WHEN '760.05.01.001' THEN 'ÇEVREYOLU YATAŞ BEDDİNG'
    WHEN '740.22.01.001' THEN 'LEAF LARA'
END,
EMFICHE.DATE_ AS [Tarih],
year(EMFICHE.DATE_)  [Yıl],
RIGHT('00'+CAST(MONTH(EMFICHE.DATE_) AS NVARCHAR(100)),2)+'-'+
CASE MONTH(EMFICHE.DATE_)
    WHEN 1 THEN 'Ocak'
    WHEN 2 THEN 'Şubat'
    WHEN 3 THEN 'Mart'
    WHEN 4 THEN 'Nisan'
    WHEN 5 THEN 'Mayıs'
    WHEN 6 THEN 'Haziran'
    WHEN 7 THEN 'Temmuz'
    WHEN 8 THEN 'Ağustos'
    WHEN 9 THEN 'Eylül'
    WHEN 10 THEN 'Ekim'
    WHEN 11 THEN 'Kasım'
    WHEN 12 THEN 'Aralık'
END AS [Ay],

	Case EMFLINE.TRCODE 
			WHEN 1 THEN 'Açılış Fişi' 
			WHEN 2 THEN 'Tahsil Fişi' 
			WHEN 3 THEN 'Tediye Fişi' 
			WHEN 4 THEN 'Mahsup Fişi' 
			WHEN 5 THEN 'Özel Fiş' 
			WHEN 6 THEN 'Kur Farkı Fişi' 
			WHEN 7 THEN 'Kapanış Fişi' 
			WHEN 8 THEN 'Enflasyon Muhasebe Fişi' 
			WHEN 9 THEN 'Konsolidasyon Düzeltme Fişi' 
			WHEN 10 THEN 'Tfrs Düzeltme Fişi' 
	END [Fiş Türü], 
	ISNULL(EMFICHE.FICHENO,'') [Fiş No],
	ISNULL(EMFICHE.JOURNALNO,'') [Yevmiye No],
	 
	ISNULL(EMFICHE.GENEXP1+''+EMFICHE.GENEXP2+''+EMFICHE.GENEXP3+''+EMFICHE.GENEXP4,'') [Genel Açıklama],
	EMUHACC.CODE [Hesap Kodu], 
	EMUHACC.DEFINITION_ [Hesap Adı],
 
	EMFLINE.DEBIT  [Borç], 
	EMFLINE.CREDIT  [Alacak],
	CASE WHEN EMFLINE.SIGN=0 THEN EMFLINE.DEBIT ELSE -EMFLINE.CREDIT  END [Borç / Alacak],
 	CASE EMFICHE.MODULENR
	WHEN 0 THEN 'Kaynak Fiş Türü Olmayanlar'
	WHEN 1 THEN 'Malzeme' 
	WHEN 2 THEN 'Satınalma' 
	WHEN 3 THEN 'Satış ve Dağıtım' 
	WHEN 4 THEN 'Cari Hesap Fişleri' 
	WHEN 5 THEN 'Çek/Senet' 
	WHEN 6 THEN 'Banka Fişleri' 
	WHEN 7 THEN 'Kasa' 
	WHEN 10 THEN 'Personel Ödemeleri' 
	WHEN 20 THEN 'Ü.E Planlanan Maliyetleri' 
	WHEN 21 THEN 'Ü.E Gerçekleşen Maliyetleri' 
	WHEN 25 THEN 'Sabit Kıymet' 
	WHEN 103 THEN 'SMM Mahsubu' 
	WHEN 201 THEN 'Dağıtım Fişleri' 
	WHEN 202 THEN 'Millileştirme Fişleri' 
	ELSE '' END [Modül Adı] 
 
	 
	FROM    dbo.LG_{{FIRMA}}_{{DONEM}}_EMFLINE EMFLINE           (NOLOCK)   INNER JOIN dbo.LG_{{FIRMA}}_{{DONEM}}_EMFICHE EMFICHE (NOLOCK) ON EMFICHE.LOGICALREF=EMFLINE.ACCFICHEREF 
	LEFT JOIN dbo.LG_{{FIRMA}}_EMUHACC EMUHACC    (NOLOCK) ON EMUHACC.LOGICALREF=EMFLINE.ACCOUNTREF 	 
	LEFT JOIN dbo.L_CAPIUSER EKLEYEN        (NOLOCK) ON EKLEYEN.NR=EMFICHE.CAPIBLOCK_CREATEDBY
	LEFT JOIN dbo.L_CAPIUSER DEGISTIREN     (NOLOCK) ON DEGISTIREN.NR=EMFICHE.CAPIBLOCK_MODIFIEDBY
	LEFT JOIN L_CAPIDIV ISYERI ON ISYERI.NR = EMFICHE.BRANCH  AND ISYERI.FIRMNR='{{FIRMA}}'
	WHERE EMFLINE.CANCELLED = 0 AND EMFICHE.CANCELLED=0 and  EMUHACC.CODE  
	  IN( 
 '740.20.01.001', 
 '740.21.01.001', 
 '760.01.01.001', 
 '760.02.01.001', 
 '760.03.01.001', 
 '760.04.01.001', 
 '760.05.01.001'  )
GO
